Repository evilwb/APRac2, pull requests merged in 2025-03, with the labels that each got.

#50 Clean up Tabora wrench upgrade flag check
  Container.py
Labels: bug

#53 Fix item scouting
  ClientCheckLocations.py
  Rac2Client.py
  __init__.py
  data/Planets.py
Labels: bug

#54 Full Weapon Randomization
  Callbacks.py
  ClientReceiveItems.py
  Container.py
  ItemPool.py
  Logic.py
  Rac2Client.py
  Rac2Interface.py
  Rac2Options.py
  __init__.py
  data/IsoAddresses.py
  data/Items.py
  data/Locations.py
  data/Planets.py
  data/RamAddresses.py
Labels: enhancement

#48 Extended weapon progression
  Callbacks.py
  Container.py
  ItemPool.py
  Rac2Client.py
  Rac2Interface.py
  Rac2Options.py
  __init__.py
  data/ExperienceTables.py
  data/IsoAddresses.py
  data/Items.py
  data/RamAddresses.py
Labels: enhancement

#66 Fix vendor quirks
  Callbacks.py
  Container.py
  Rac2Interface.py
  data/IsoAddresses.py
  data/Items.py
Labels: bug

#67 Add item & location groups
  __init__.py
  data/Items.py
  data/Planets.py
Labels: enhancement

#71 Fix Ammo Crate Crash
  Container.py
  data/IsoAddresses.py
Labels: bug

#74 Fix weapon experience multiplier option range
  Rac2Options.py
  Simplified Ratchet & Clank 2.yaml
Labels: bug

#75 Fix vendor refresh issues for remote items
  Callbacks.py
  ClientCheckLocations.py
  ClientReceiveItems.py
  Rac2Interface.py
  data/Locations.py
Labels: bug

#77 Remove useless cutscenes rarely causing crashes
  Callbacks.py
  Rac2Client.py
  data/IsoAddresses.py
  data/RamAddresses.py
Labels: bug

#80 Fix The Ammo Crash Fix.
  Container.py
  data/IsoAddresses.py
Labels: bug

#79 Fix Damosel Pyramid PB logic
  data/Locations.py
Labels: bug, logic

#78 Fixed vendor slots not unlocking if owning Lv2+ vanilla weapon
  Container.py
  data/IsoAddresses.py
Labels: bug

#81 Fix common exception when landing on Yeedil
  Rac2Client.py
Labels: bug

#84 Cutscene QOL
  Callbacks.py
  Container.py
  data/RamAddresses.py
Labels: enhancement

#86 Fix custom data auto-save issues
  Container.py
  data/IsoAddresses.py
  data/Items.py
  data/RamAddresses.py
Labels: bug
